### ISSUE TITLE
결과종이

### ISSUE THREAD

**Issue by Leebonggu** [FromRagsToRich/Lottos#3]
## What Issue

결과지 만들기

## Todo
- [ ] 실제 판매되는 로또종이처럼
- [ ] 이미지 다운로드 가능?
- [ ] 결과 이후 리셋
